#![forbid(unsafe_code)]
//! The F1 help overlay: keymap, file-operation semantics, durability contract (design 8,
//! NFR-DUR).

pub const TEXT: &[&str] = &[
    "KEYS (command line empty)",
    "  Enter            enter directory / open file with xdg-open",
    "  Backspace        parent directory          Alt+Up    parent directory",
    "  Home / End       first / last entry        Ctrl+A     mark all",
    "  Ctrl+U           swap panels               Space      mark (directory: size)",
    "  Esc              stop a directory that is still loading",
    "KEYS (always)",
    "  Tab              other panel               Up/Down/PgUp/PgDn  cursor",
    "  Insert           mark and move down",
    "  Alt+= / Alt+- / Alt+*   mark by glob / unmark by glob / invert marks",
    "  Ctrl+S           quick search              Alt+.      hidden files",
    "  Ctrl+R           re-read both panels       Alt+Left/Right  history",
    "  Alt+Enter        insert quoted name        Alt+P      insert quoted path",
    "  Ctrl+O           show the last command's output",
    "  Ctrl+F3..F6      sort by name, extension, size, time (again: reverse)",
    "  F3 view  F4 edit  Shift+F4 new file  F5 copy  F6 move  Shift+F6 rename",
    "  F7 mkdir  F8 trash  Shift+F8 delete permanently  F10, Alt+X quit",
    "  Ctrl+T new tab  Ctrl+W close tab  Alt+PgUp/PgDn previous/next tab  Ctrl+1..9 tab",
    "COMMAND LINE (text typed)",
    "  Enter runs the line with $SHELL -c in the panel's directory; cd <dir> changes",
    "  the panel. Ctrl+A/E start/end, Ctrl+U/K kill to start/end, Ctrl+W kill word,",
    "  Ctrl+P/N history, Esc clears.",
    "",
    "FILE OPERATIONS",
    "  Copy never shows a partial file: data goes to .<name>.mc-partial-<random>",
    "  and is renamed into place. An existing file is replaced only after you answer",
    "  Overwrite; the old file is never truncated. Symbolic links are copied as links.",
    "  Not preserved: ownership, ACLs, xattrs, hard-link structure, sparseness.",
    "  Move renames when it can. Across filesystems it copies, then deletes the source",
    "  only after the copy is durable (syncfs); a changed source is kept. On vfat and",
    "  exfat the change check is best-effort. Mount points are never copy-deleted.",
    "  Trash follows the freedesktop.org specification; it never copies across",
    "  filesystems and never deletes. Shift+F8 deletes only after you type delete.",
    "",
    "DURABILITY",
    "  Copy does not fsync, like cp. Move keeps every file in at least one complete,",
    "  committed place at every moment, also across a crash on filesystems that",
    "  honour syncfs (btrfs, ext4, xfs). A crash can leave the last batch in both",
    "  places, never in neither. After a crash, .mc-partial-* files may remain; they",
    "  are never deleted automatically.",
];
